<?php
###################################
##  See license.txt for license  ##
###################################

$modversion['name'] = _MI_xforms_NAME;
$modversion['version'] = '1.2';
$modversion['description'] = _MI_xforms_DESC;
$modversion['author'] = "XD Soft";
$modversion['credits'] = "Creator of xforms Dylian Melgert and special thanks to Brandycoke Productions (http://www.brandycoke.com/) for creating liaise (The base of this module)";
$modversion['help'] = "";
$modversion['license'] = "GPL (http://creativecommons.org/licenses/GPL/2.0/)";
$modversion['official'] = 0;
$modversion['image'] = "images/xforms.png";
$modversion['dirname'] = "xforms";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xforms_forms";
$modversion['tables'][1] = "xforms_formelements";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu -- content in main menu block
$modversion['hasMain'] = 1;

$modversion['onInstall'] = 'include/functions.php';

// Templates
$modversion['templates'][1]['file'] = 'xforms_index.html';
$modversion['templates'][1]['description'] = _MI_xforms_TMPL_MAIN_DESC;
$modversion['templates'][2]['file'] = 'xforms_form.html';
$modversion['templates'][2]['description'] = _MI_xforms_TMPL_FORM_DESC;
$modversion['templates'][3]['file'] = 'xforms_error.html';
$modversion['templates'][3]['description'] = _MI_xforms_TMPL_ERROR_DESC;

//	Module Configs
// $xoopsModuleConfig['t_width']
$modversion['config'][1]['name'] = 't_width';
$modversion['config'][1]['title'] = '_MI_xforms_TEXT_WIDTH';
$modversion['config'][1]['description'] = '';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = '35';

// $xoopsModuleConfig['t_max']
$modversion['config'][2]['name'] = 't_max';
$modversion['config'][2]['title'] = '_MI_xforms_TEXT_MAX';
$modversion['config'][2]['description'] = '';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = '255';

// $xoopsModuleConfig['ta_rows']
$modversion['config'][3]['name'] = 'ta_rows';
$modversion['config'][3]['title'] = '_MI_xforms_TAREA_ROWS';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = '5';

// $xoopsModuleConfig['ta_cols']
$modversion['config'][4]['name'] = 'ta_cols';
$modversion['config'][4]['title'] = '_MI_xforms_TAREA_COLS';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = '35';

// $xoopsModuleConfig['moreinfo']
$modversion['config'][5]['name'] = 'moreinfo';
$modversion['config'][5]['title'] = '_MI_xforms_MOREINFO';
$modversion['config'][5]['description'] = '';
$modversion['config'][5]['formtype'] = 'select_multi';
$modversion['config'][5]['valuetype'] = 'array';
$modversion['config'][5]['default'] = array('user', 'ip', 'agent');
$modversion['config'][5]['options'] = array(_MI_xforms_MOREINFO_USER => 'user', _MI_xforms_MOREINFO_IP => 'ip', _MI_xforms_MOREINFO_AGENT => 'agent', _MI_xforms_MOREINFO_FORM => 'form');

// $xoopsModuleConfig['mail_charset']
$modversion['config'][6]['name'] = 'mail_charset';
$modversion['config'][6]['title'] = '_MI_xforms_MAIL_CHARSET';
$modversion['config'][6]['description'] = '_MI_xforms_MAIL_CHARSET_DESC';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = _CHARSET;

// $xoopsModuleConfig['prefix']
$modversion['config'][7]['name'] = 'prefix';
$modversion['config'][7]['title'] = '_MI_xforms_PREFIX';
$modversion['config'][7]['description'] = '';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = '';

// $xoopsModuleConfig['suffix']
$modversion['config'][8]['name'] = 'suffix';
$modversion['config'][8]['title'] = '_MI_xforms_SUFFIX';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = '*';

// $xoopsModuleConfig['intro']
$modversion['config'][9]['name'] = 'intro';
$modversion['config'][9]['title'] = '_MI_xforms_INTRO';
$modversion['config'][9]['description'] = '';
$modversion['config'][9]['formtype'] = 'textarea';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['default'] = _MI_xforms_INTRO_DEFAULT;

// $xoopsModuleConfig['intro']
$modversion['config'][9]['name'] = 'noform';
$modversion['config'][9]['title'] = '_MI_xforms_NOFORM';
$modversion['config'][9]['description'] = '';
$modversion['config'][9]['formtype'] = 'textarea';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['default'] = _MI_xforms_NOFORM_DEFAULT;

// $xoopsModuleConfig['global']
$modversion['config'][10]['name'] = 'global';
$modversion['config'][10]['title'] = '_MI_xforms_GLOBAL';
$modversion['config'][10]['description'] = '';
$modversion['config'][10]['formtype'] = 'textarea';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = _MI_xforms_GLOBAL_DEFAULT;

// $xoopsModuleConfig['uploaddir']
$modversion['config'][11]['name'] = 'uploaddir';
$modversion['config'][11]['title'] = '_MI_xforms_UPLOADDIR';
$modversion['config'][11]['description'] = '_MI_xforms_UPLOADDIR_DESC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'text';
$modversion['config'][11]['default'] = XOOPS_UPLOAD_PATH.'/'.uniqid(rand());

// $xoopsModuleConfig['captcha']  
$modversion['config'][12]['name'] = 'captcha';  
$modversion['config'][12]['title'] = '_MI_xforms_CAPTCHA';  
$modversion['config'][12]['description'] = '_MI_xforms_CAPTCHADSC';  
$modversion['config'][12]['formtype'] = 'yesno';  
$modversion['config'][12]['valuetype'] = 'int';  
$modversion['config'][12]['default'] = 1;

?>