<?php
###################################
##  See license.txt for license  ##
###################################

$modversion['name'] = _MI_xforms_NAME;
$modversion['version'] = '1.21';
$modversion['description'] = _MI_xforms_DESC;
$modversion['author'] = "XD Soft";
$modversion['credits'] = "Creator of xforms Dylian Melgert and special thanks to Brandycoke Productions (http://www.brandycoke.com/) for creating liaise (The base of this module)";
$modversion['help'] = "page=help";
$modversion['license'] = "GNU GPL";
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/xforms.png";
$modversion['dirname'] = "xforms";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date']     = '2012/06/25';
$modversion["module_website_url"] = "www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"] = "Final";
$modversion['min_php']='5.2';
$modversion['min_xoops']="2.5.5";
$modversion['min_admin']='1.1';
$modversion['min_db']= array('mysql'=>'5.0.7', 'mysqli'=>'5.0.7');

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xforms_forms";
$modversion['tables'][1] = "xforms_formelements";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu -- content in main menu block
$modversion['hasMain'] = 1;

$modversion['onInstall'] = 'include/functions.php';
$modversion['system_menu'] = 1;


// Templates
$modversion['templates'][1]['file'] = 'xforms_index.html';
$modversion['templates'][1]['description'] = _MI_xforms_TMPL_MAIN_DESC;
$modversion['templates'][2]['file'] = 'xforms_form.html';
$modversion['templates'][2]['description'] = _MI_xforms_TMPL_FORM_DESC;
$modversion['templates'][3]['file'] = 'xforms_error.html';
$modversion['templates'][3]['description'] = _MI_xforms_TMPL_ERROR_DESC;

//	Module Configs
// Module config setting
$i=1;
// $xoopsModuleConfig['t_width']
$modversion['config'][$i]['name'] = 't_width';
$modversion['config'][$i]['title'] = '_MI_xforms_TEXT_WIDTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '35';
$i++;
// $xoopsModuleConfig['t_max']
$modversion['config'][$i]['name'] = 't_max';
$modversion['config'][$i]['title'] = '_MI_xforms_TEXT_MAX';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '255';
$i++;
// $xoopsModuleConfig['ta_rows']
$modversion['config'][$i]['name'] = 'ta_rows';
$modversion['config'][$i]['title'] = '_MI_xforms_TAREA_ROWS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '5';
$i++;
// $xoopsModuleConfig['ta_cols']
$modversion['config'][$i]['name'] = 'ta_cols';
$modversion['config'][$i]['title'] = '_MI_xforms_TAREA_COLS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '35';
$i++;
// $xoopsModuleConfig['moreinfo']
$modversion['config'][$i]['name'] = 'moreinfo';
$modversion['config'][$i]['title'] = '_MI_xforms_MOREINFO';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('user', 'ip', 'agent');
$modversion['config'][$i]['options'] = array(_MI_xforms_MOREINFO_USER => 'user', _MI_xforms_MOREINFO_IP => 'ip', _MI_xforms_MOREINFO_AGENT => 'agent', _MI_xforms_MOREINFO_FORM => 'form');
$i++;
// $xoopsModuleConfig['mail_charset']
$modversion['config'][$i]['name'] = 'mail_charset';
$modversion['config'][$i]['title'] = '_MI_xforms_MAIL_CHARSET';
$modversion['config'][$i]['description'] = '_MI_xforms_MAIL_CHARSET_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _CHARSET;
$i++;
// $xoopsModuleConfig['prefix']
$modversion['config'][$i]['name'] = 'prefix';
$modversion['config'][$i]['title'] = '_MI_xforms_PREFIX';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
// $xoopsModuleConfig['suffix']
$modversion['config'][$i]['name'] = 'suffix';
$modversion['config'][$i]['title'] = '_MI_xforms_SUFFIX';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '*';
$i++;
// $xoopsModuleConfig['intro']
$modversion['config'][$i]['name'] = 'intro';
$modversion['config'][$i]['title'] = '_MI_xforms_INTRO';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _MI_xforms_INTRO_DEFAULT;
$i++;
// $xoopsModuleConfig['intro']
$modversion['config'][$i]['name'] = 'noform';
$modversion['config'][$i]['title'] = '_MI_xforms_NOFORM';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _MI_xforms_NOFORM_DEFAULT;
$i++;
// $xoopsModuleConfig['global']
$modversion['config'][$i]['name'] = 'global';
$modversion['config'][$i]['title'] = '_MI_xforms_GLOBAL';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _MI_xforms_GLOBAL_DEFAULT;
$i++;
// $xoopsModuleConfig['uploaddir']
$modversion['config'][$i]['name'] = 'uploaddir';
$modversion['config'][$i]['title'] = '_MI_xforms_UPLOADDIR';
$modversion['config'][$i]['description'] = '_MI_xforms_UPLOADDIR_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XOOPS_UPLOAD_PATH.'/'.uniqid(rand());
$i++;
// $xoopsModuleConfig['captcha']  
$modversion['config'][$i]['name'] = 'captcha';  
$modversion['config'][$i]['title'] = '_MI_xforms_CAPTCHA';  
$modversion['config'][$i]['description'] = '_MI_xforms_CAPTCHADSC';  
$modversion['config'][$i]['formtype'] = 'yesno';  
$modversion['config'][$i]['valuetype'] = 'int';  
$modversion['config'][$i]['default'] = 1;